---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3291879972-m4wYCDfxL5c10aY1OxnBdzvbssXh8uPSkIJN6WC
:access_token_secret: WfvQumdUO7mS4v4X89NKCQAAs1nZBkJPTmHQyJzYyTW3c
